# Generated by Django 3.0.6 on 2020-05-29 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Shipped', 'Shipped'), ('Abandoned', 'Abandoned'), ('Delivered', 'Delivered')], default='Shipped', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('company_name', models.CharField(blank=True, max_length=75, null=True)),
                ('country', models.CharField(choices=[('Nepal', 'Nepal')], default='Nepal', max_length=10)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('Direct bank transfer', 'Direct bank transfer'), ('Cheque payments', 'Cheque payments'), ('Cash on delivery', 'Cash on delivery')], max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
