# Generated by Django 3.0.6 on 2020-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200516_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
