# Generated by Django 3.0.6 on 2020-05-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200516_1441'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'product_code')},
        ),
    ]
